### ISSUE TITLE
Other termination criteria for evolutionary algorithm

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#101]
After PR #100 has added the Java interface for termination criteria for our evolutionary plan enumeration algorithm, including a straightforward example implementation of this interface, it is now possible to define and implement other possible termination criteria that we want to consider in the paper. The purpose of this issue is to do just that.

Before anything is implemented, the criteria should be defined, at least informally.

**Comment by chengsijin0817** [comment]
This issue has been addressed by PR #114
