### ISSUE TITLE
Optimizer that uses an evolutionary algorithm

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#23]
Probably, it would be better to attempt the implementation of this optimizer only after the basic, DP-based one (#22) is in place.

**Comment by hartig** [comment]
The main part of this issue has been addressed in PR #96 

However, to complete the work on the optimizer, issues #92 and #98 still need to be addressed (or, @chengsijin0817, is there anything else that is also still missing?)

**Comment by chengsijin0817** [comment]
> The main part of this issue has been addressed in PR #96
> 
> However, to complete the work on the optimizer, issues #92 and #98 still need to be addressed (or, @chengsijin0817, is there anything else that is also still missing?)

No.  At the moment I can't think of anything else missing.
I will take care of issues #92 and #98

**Comment by chengsijin0817** [comment]
Issues #92 and #98 have been addressed.
