### ISSUE TITLE
Logical optimization: merge requests to same fed.member

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#261]
If there is a join(req,req) or an mj{ ..., req, ..., req, ... } in which both of the req children operators are for the same federation member and the request expressions can be merged for that federation member (e.g., two triple patterns or two BGP for a SPARQL endpoint), then merge the req operators into one and replace the join by the merged req operator. Similar if there are tpAdd(req) or bgpAdd(req) cases that can be merged.

**Comment by hartig** [comment]
I have addressed this TODO by implementing the `MergeRequests` heuristic, including unit tests. See commit https://github.com/LiUSemWeb/HeFQUIN/commit/9df30bb9f12fd29712486a40903ab442820f2841

/cc @chengsijin0817

**Comment by chengsijin0817** [comment]
> I have addressed this TODO by implementing the `MergeRequests` heuristic, including unit tests. See commit [9df30bb](https://github.com/LiUSemWeb/HeFQUIN/commit/9df30bb9f12fd29712486a40903ab442820f2841)
> 
> /cc @chengsijin0817

Thanks! ;-)
