### ISSUE TITLE
Remove CLI arguments for setting federation members

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#262]
Now that we have the `--federationDescription` argument for the CLI, the other arguments for setting federation members (e.g., `--considerSPARQLEndpoint`) are somewhat obsolete and can be removed, I think.

Before I go ahead and remove them, I wanted to ask: @chengsijin0817 @scferrada do you agree that they can be removed or do you see any uses cases for which we may want to keep them?

**Comment by chengsijin0817** [comment]
Hi @hartig , I agree to remove them.

**Comment by scferrada** [comment]
Hi, if the `--federationDescription` file argument can include Cypher or GraphQL endpoints as well, then I agree that `--considerXXX` arguments may be removed.

**Comment by hartig** [comment]
> [...] if the `--federationDescription` file argument can include Cypher or GraphQL endpoints [...]

It does. See https://github.com/LiUSemWeb/HeFQUIN/blob/main/ExampleFederation.ttl for an example.
