### ISSUE TITLE
Instrument executable plans to record statistics

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#28]
Note that this is _not_ about statistics that can be used for future query planning but just for debugging and experiments. For instance, we may want to measure the selectivity of joins and compare the measurements to the estimates that were determined and used during query planning.

**Comment by hartig** [comment]
PR #140 provides a basis for addressing this issue.

**Comment by hartig** [comment]
Commit https://github.com/LiUSemWeb/HeFQUIN/commit/d79da698f86593841961464f4a4bcb82f01012b4 addresses this TODO.

@chengsijin0817 I have extended all the executable operators to collect some generic stats about themselves (e.g., how many input mappings did they consume, how much time did they need for processing each block of input mappings). All these statistics of the whole executable plan and all its operators are accessible as a tree of Stats objects within the `ExecutionStats` objects that is part of an `QueryProcStats` object. Hence, this is now the properly implemented version of the quick'n'dirty hack that we talked about in our recent meeting. An example of what it looks like to print out such a `QueryProcStats` object for an example DBpedia query is:
```
overallQueryProcessingTime : 1320
planningTime : 6
compilationTime : 3
executionTime : 1311
queryPlanningStats : {
  overallQueryPlanningTime : 6
  sourcePlanningTime : 3
  queryOptimizationTime : 3
  sourcePlanningStats : { }
  queryOptimizationStats : { }
}
executionStats : {
  planStats : {
    rootOperatorStats : {
      classNameOfOperator : ExecOpBinaryUnion
      shortStringOfOperator : se.liu.ida.hefquin.engine.queryplan.executable.impl.ops.ExecOpBinaryUnion@4fad9bb2
      leftInputConsumed : true
      rightInputConsumed : true
      numberOfLeftInputBlocksProcessed : 1
      numberOfLeftInputMappingsProcessed : 1
      averageProcTimePerLeftInputBlock : 0.0
      minimumProcTimePerLeftInputBlock : 0
      maximumProcTimePerLeftInputBlock : 0
      numberOfRightInputBlocksProcessed : 2
      numberOfRightInputMappingsProcessed : 2
      averageProcTimePerRightInputBlock : 0.0
      minimumProcTimePerRightInputBlock : 0
      maximumProcTimePerRightInputBlock : 0
    }
    numberOfSubPlans : 2
    subPlanStats : [
      {
        rootOperatorStats : {
          classNameOfOperator : ExecOpRequestSPARQL
          shortStringOfOperator : se.liu.ida.hefquin.engine.queryplan.executable.impl.ops.ExecOpRequestSPARQL@38831718
          numberOfInvocations : 1
          overallExecTime : 1062
          requestAsString : (bgp (triple http://dbpedia.org/resource/Berlin @http://xmlns.com/foaf/0.1/name ?o)  )
          fedMemberAsString : se.liu.ida.hefquin.cli.modules.ModFederation$1@2a448449
          requestExecTime : 0
          responseProcTime : 1062
        }
        numberOfSubPlans : 0
        subPlanStats : [ ]
      }
      {
        rootOperatorStats : {
          classNameOfOperator : ExecOpRequestSPARQL
          shortStringOfOperator : se.liu.ida.hefquin.engine.queryplan.executable.impl.ops.ExecOpRequestSPARQL@32f232a5
          numberOfInvocations : 1
          overallExecTime : 130
          requestAsString : (bgp (triple http://dbpedia.org/resource/Hamburg @http://xmlns.com/foaf/0.1/name ?o)  )
          fedMemberAsString : se.liu.ida.hefquin.cli.modules.ModFederation$1@2a448449
          requestExecTime : 0
          responseProcTime : 130
        }
        numberOfSubPlans : 0
        subPlanStats : [ ]
      }
    ]
  }
}
```

**Comment by chengsijin0817** [comment]
Hi Olaf, thanks a lot for extending the executable operators. It helps a lot for observing the execution process. 
When I ran the experiment with queries from FedBench, for three of the six queries, an exception occurs in class "BinaryExecutableOpBase" (lines 136 and 142). 
"Failure:/ by zero
java.lang.ArithmeticException: / by zero at se.liu.ida.hefquin.engine.queryplan.executable.impl.ops.BinaryExecutableOpBase.createStats(BinaryExecutableOpBase.java:142)"

Could you please look at how to deal with this issue?

**Comment by hartig** [comment]
Ah, I was not thinking of the possibility that the calculation of the stats may result in a division by zero. I have fixed this bug in commit https://github.com/LiUSemWeb/HeFQUIN/commit/639f74dad30a97ef007510f209e73226f294d1bc

**Comment by chengsijin0817** [comment]
Thanks! It works well now.
