### ISSUE TITLE
Convert vocabularies to OWL ontologies

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/HeFQUIN#361]
In order to use automated ontology documentation tools, such as [pyLODE](https://github.com/RDFLib/pyLODE), we need to convert the vocabularies into OWL ontologies.

Converting them to OWL is straightforward since  we simply need to: 1) state that the vocabulary is an `owl:Ontology`, and 2) change all instances `rdf:class` to instances of `owl:Class`.

For example
```turtle
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:    <http://www.w3.org/2000/10/XMLSchema#> .
@prefix dc:     <http://purl.org/dc/elements/1.1/> .
@prefix lr:     <http://w3id.org/hefquin/lpg2rdf#> .

<http://w3id.org/hefquin/lpg2rdf>
    dc:creator       "Olaf Hartig" ;
    dc:date          "2023-11-29" ;
    dc:format        "RDF" ;
    dc:identifier    <http://w3id.org/hefquin/lpg2rdf> ;
    dc:title         "Vocabulary for describing LPG-to-RDF configurations"@en ;
    rdfs:label       "Vocabulary for describing LPG-to-RDF configurations"@en ;
    dc:description   "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en ;
    rdfs:comment     "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en .

## ==== CLASS DECLARATIONS ====

lr:LPGtoRDFConfiguration rdf:type rdfs:Class ;
    rdfs:label      "LPG-to-RDF Configuration"@en ;
    rdfs:comment    "Class of LPG-to-RDF configurations. Instances of this class must have exactly one lr:nodeMapping property, one lr:nodeLabelMapping property, one lr:edgeLabelMapping property, one lr:propertyNameMapping property, and one lr:labelPredicate property."@en .
```

would become:

```turtle
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:    <http://www.w3.org/2002/07/owl#> .
@prefix xsd:    <http://www.w3.org/2000/10/XMLSchema#> .
@prefix dc:     <http://purl.org/dc/elements/1.1/> .
@prefix lr:     <http://w3id.org/hefquin/lpg2rdf#> .

<http://w3id.org/hefquin/lpg2rdf>
    a owl:Ontology ;
    dc:creator       "Olaf Hartig" ;
    dc:date          "2023-11-29" ;
    dc:format        "RDF" ;
    dc:identifier    <http://w3id.org/hefquin/lpg2rdf> ;
    dc:title         "Vocabulary for describing LPG-to-RDF configurations"@en ;
    rdfs:label       "Vocabulary for describing LPG-to-RDF configurations"@en ;
    dc:description   "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en ;
    rdfs:comment     "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en .

## ==== CLASS DECLARATIONS ====

lr:LPGtoRDFConfiguration
    a owl:Class ;
    rdfs:label      "LPG-to-RDF Configuration"@en ;
    rdfs:comment    "Class of LPG-to-RDF configurations. Instances of this class must have exactly one lr:nodeMapping property, one lr:nodeLabelMapping property, one lr:edgeLabelMapping property, one lr:propertyNameMapping property, and one lr:labelPredicate property."@en .
```

**Comment by keski** [comment]
The branch [361-convert-vocabularies-to-owl-ontologies](https://github.com/LiUSemWeb/HeFQUIN/tree/361-convert-vocabularies-to-owl-ontologies) contains the converted ontologies (renamed `engineconf.ttl` and `lpg2rdfconf.ttl`) according to the pattern above. See https://liusemweb.github.io/HeFQUIN/vocab/engineconf/latest/index.html and https://liusemweb.github.io/HeFQUIN/vocab/lpg2rdfconf/latest/index.html for examples generated based on these files using pyLODE.

**Note:** Before merging into main we should update `hefquin-vocabs/build.sh` and confirm that the generated files are correct. I managed to make the generation work for `procECVocab` but not for `procLPGtoRDF`. We also need to update the update the example configuration files.

**Comment by hartig** [comment]
> The branch [361-convert-vocabularies-to-owl-ontologies](https://github.com/LiUSemWeb/HeFQUIN/tree/361-convert-vocabularies-to-owl-ontologies) contains the converted ontologies (renamed engineconf.ttl and lpg2rdfconf.ttl) according to the pattern above.

I have created a (draft) PR from the branch to make it easier (at least for me) to see the differences. See #362 

> See https://liusemweb.github.io/HeFQUIN/vocab/engineconf/latest/index.html and https://liusemweb.github.io/HeFQUIN/vocab/lpg2rdfconf/latest/index.html for examples generated based on these files using pyLODE.

Thanks. That's very helpful! Two observations about these pyLODE renderings:
1. The table of contents (TOC) on the RHS of these pages seems to be based on the rdfs:label and looks a bit weird. Perhaps the actual issue here is that I have used rdfs:label wrongly?
2. The engine conf. vocabulary also contains a number of instances. These are not in the page (at least not in the TOC).
