### ISSUE TITLE
publish docker image

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/HeFQUIN#364]
This issue is about publishing docker images for HeFQUIN releases on ghcr.io. Starting up HefQUIN as a docker container will then be a simple as:
```bash
docker run ghcr.io/liusemweb/hefquin
```
with additional arguments for configuration.

I'd suggest that we add an action that is  triggered automatically whenever a new release is published. The image should be built and published with both the release tag and the tag `latest`.

For testing purposes, it should also be possible to trigger the workflow manually via the GitHub Actions tab. I'd suggest that when triggered manually we tag the version with `dev` to avoid confusing it with stable releases (i.e., `latest`).

@hartig

**Comment by hartig** [comment]
Sounds all good!

**Comment by keski** [comment]
Apparently we need to enable public packages on the group level (`LiUSemWeb`). Right now all packages become private by default. For example, under `Packages` (found under `Releases`) the docker image is currently listed as private:

<img width="752" alt="Screenshot 2024-10-02 at 21 24 41" src="https://github.com/user-attachments/assets/5a51cafc-4524-4b6f-9371-01e2a1868abd">

@hartig , do you have permission to change the package settings?

**Comment by hartig** [comment]
I have changed the setting to 'public' on the level of the organization (LiUSemWeb). Can you please check whether it works now.

**Comment by keski** [comment]
The package is still listed as private... Also tried republishing  but it had no effect.

**Comment by keski** [comment]
That worked! I hope you don't have to set the permissions manually each time. I'll try regenerating the package to see what happens.

**Comment by keski** [comment]
For docker images it seems to be working nicely! I'll test maven packages later today and report back.

**Comment by hartig** [comment]
Nice!

Ready to turn the corresponding branch into a PR?

**Comment by keski** [comment]
Almost. I have just have a small addition to make in the workflow so that the version tag is picked up and added to the published docker image.
