### ISSUE TITLE
simplify version management

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/HeFQUIN#368]
In the current setup, we have to manually set the version number of each module before release. This is cumbersome and error prone. Instead, we can use:
```bash
mvn versions:set -DnewVersion=x.y.z -DgenerateBackupPoms=false
```
to update the version number across all module pom files simultaneously.

The only adaptation we need to make is to drop the `project.version` from the properties in the main pom and use the maven default value instead (which is the same as the project version).

**Comment by hartig** [comment]
Great! I was already wondering how we can update the versions in all the modules without having to touch every POM file manually.

In addition to making this change in the main POM, can you please create a new Wiki page for collecting notes related to "Release Logistics" and, then, add a note about updating the version number, including the command you mention above. Additionally, the Wiki page should have notes related to the other release-related topics that came up recently (compiling the WAR, the Maven repo, the Maven dependency blob, the docker image). Later we can turn this Wiki page into a page of the Website.

**Comment by keski** [comment]
I've now prepared the a [Release Logistics](https://github.com/LiUSemWeb/HeFQUIN/wiki/Release-Logistics) page. Please check it out to see if it looks okay and that nothing is missing.

**Comment by keski** [comment]
An alternative to having a changelog file in the project root would be to manage the changelog in a wiki page. But I suspect we will forget to update such a page, and keeping it as part of the feature branch feels more robust.
