### ISSUE TITLE
Fix VALUES-based bind join

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#45]
...as per the discussion in https://github.com/LiUSemWeb/HeFQUIN/pull/44#discussion_r635914062

That is, use the same idea to fix as mentioned in https://github.com/LiUSemWeb/HeFQUIN/pull/44#discussion_r635182694 for the UNION-based bind join.

**Comment by scferrada** [comment]
This was addressed in #34

**Comment by hartig** [comment]
Actually, it was addressed in PR #44
