### ISSUE TITLE
Upgrade to Jena 4.1

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#55]
We should upgrade the code base as soon as possible to Jena 4.1 because that version brings the latest updates for RDF-star. I did a check and noticed that there are several things that need to be changed since some classes have changed from Jena 3.17 to Jena 4.x. Hence, upgrading is not entirely trivial and we may not want to have other active PRs at the same time.

The announcement of Jena 4.0 with a list of changes can be found at:
https://lists.apache.org/thread.html/r64bc917638f6964843181a95a2d92bfe8cf013b06eddf4402080669b%40%3Cusers.jena.apache.org%3E

**Comment by scferrada** [comment]
I think I could take this one, since it is needed for the Cypher translations. Should I close PR #50 ? It is the only active PR at the moment.

**Comment by hartig** [comment]
Okay take it, but please create a separate PR for it instead of putting the Cypher-related stuff into the same PR. Then, feel free to merge this PR and move on to the Cypher stuff.

**Comment by scferrada** [comment]
Resolved with #56
