### ISSUE TITLE
Dynamic Programming algorithm for query planning

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#71]
The current implementation of the optimizer in `se.liu.ida.hefquin.engine.queryproc.impl.optimizer.dynamicProgramming` is not actually implementing the classical DP algorithm. It should be replaced by a correct implementation.

Besides the original description in the paper by Selinger et al., the are several descriptions in database textbooks. For instance, [Ramakrishnan and Gehrke (3rd ed)](https://github.com/pforpallav/school/blob/master/CPSC404/Ramakrishnan%20-%20Database%20Management%20Systems%203rd%20Edition.pdf) have such a description in Sec.15.4.2 (pages 496ff), and so do [Garcia-Molina et al. (2nd ed)](https://people.inf.elte.hu/kiss/DB/ullman_the_complete_book.pdf) in Sec.16.6.4 (pages 819ff).

In fact, there are two version of the algorithm, a simplified one that focuses only on left-deep plans and a more general one that can also considers bushy plans. Ramakrishnan and Gehrke cover only the first one, whereas Garcia-Molina et al. cover both.

Speaking of versions, there is also an extension of the DP algorithm that is called _iterative dynamic programming_. I will check out what this is. According to [Kossmann's survey on The State of the Art in Distributed Query Processing](https://doi.org/10.1145/371578.371598), _"this extended algorithm is adaptive and produces as good plans as basic dynamic programming for simple queries and “as good as possible plans” for complex queries for which dynamic programming is not viable."_

/cc @chengsijin0817

**Comment by hartig** [comment]
I skimmed the [paper that introduces the iterative dynamic programming algorithm](https://doi.org/10.1145/352958.352982) mentioned above. First of all, this paper also contains a description of the classical DP algorithm (Sec.3.1), including a pseudo-code representation thereof (Fig.1). Additionally, as another baseline, the paper introduces a greedy algorithm (Sec.4.1 and Fig.3) which is almost the same as the algorithm that we currently have in `se.liu.ida.hefquin.engine.queryproc.impl.optimizer.dynamicProgramming` (the only major difference is that the greedy algorithm in the paper can produce bushy plans whereas ours focuses only on left-deep plans and, thus, is even a bit simpler). The iterative dynamic programming algorithm combines the DP algorithm with the greedy algorithm: Essentially, it performs the stages of the DP algorithm until it runs out of resources (typically, main memory to keep all the possible combinations), at which point it throws away everything except for the best plan at this stage and, then, uses this best plan as the only input for further stages of DP.

Now, I think that, in addition to implementing the DP algorithm, we should also keep our greedy algorithm and use it as another competitor in the paper. Regarding the iterative DP algorithm, I think we can ignore it for the moment.

**Comment by chengsijin0817** [comment]
This issue has been addressed by PR #118
