### ISSUE TITLE
Potential mistake in two cost functions

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#84]
When working on PR #83 I noticed a possible mistake in the implementation of two of the (operator-specific) cost metrics, namely the one about number of RDF terms shipped in responses and number of variables shipped in responses. These implementations are now in the classes `CFRNumberOfTermsShippedInResponses` and `CFRNumberOfVarsShippedInResponses`, respectively. The mistake that I mean is described in the TODO comment in [lines 66-68](https://github.com/LiUSemWeb/HeFQUIN/blob/7f6c12c012a5d9de26d4aa30cfa03d6f2195e935/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/costmodel/CFRNumberOfTermsShippedInResponses.java#L66) and [lines 64-66](https://github.com/LiUSemWeb/HeFQUIN/blob/7f6c12c012a5d9de26d4aa30cfa03d6f2195e935/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/costmodel/CFRNumberOfVarsShippedInResponses.java#L64), respectively.

@chengsijin0817 can you please take a look at this and check whether my suspicion is right. In this case, maybe you also have to change the corresponding part in the paper?

**Comment by chengsijin0817** [comment]
> When working on PR #83 I noticed a possible mistake in the implementation of two of the (operator-specific) cost metrics, namely the one about number of RDF terms shipped in responses and number of variables shipped in responses. These implementations are now in the classes `CFRNumberOfTermsShippedInResponses` and `CFRNumberOfVarsShippedInResponses`, respectively. The mistake that I mean is described in the TODO comment in [lines 66-68](https://github.com/LiUSemWeb/HeFQUIN/blob/7f6c12c012a5d9de26d4aa30cfa03d6f2195e935/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/costmodel/CFRNumberOfTermsShippedInResponses.java#L66) and [lines 64-66](https://github.com/LiUSemWeb/HeFQUIN/blob/7f6c12c012a5d9de26d4aa30cfa03d6f2195e935/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/costmodel/CFRNumberOfVarsShippedInResponses.java#L64), respectively.
> 
> @chengsijin0817 can you please take a look at this and check whether my suspicion is right. In this case, maybe you also have to change the corresponding part in the paper?

Hi, I have revised these two cost functions. 
To take care of the different types of graph patterns in SPARQL requests, I also added a method in QueryPatternUtils: getVariablesInPattern(final SPARQLGraphPattern queryPattern). Please check them.

The corresponding part in the paper was defined in terms of the type of federation member.

**Comment by hartig** [comment]
See my comments in the PR, and thanks also for checking the corresponding part in the paper. Good to know that it was correct there!
