### ISSUE TITLE
Add rewriting rules

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#92]
Now that we have the framework for plan rewriting in place, the rewriting rules can be added.

@chengsijin0817 this is ready for you to continue now. Notice that I have refactored things a bit, after #70. Most importantly, for the sake of simplicity, I have merged the two concrete classes for the example rule into just one file with only one actual class (see: [RuleConvertTPAddIndexNLJToHashJoin.java](https://github.com/LiUSemWeb/HeFQUIN/blob/main/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleConvertTPAddIndexNLJToHashJoin.java)). You can use the same pattern for the other rules.

**Comment by chengsijin0817** [comment]
> Now that we have the framework for plan rewriting in place, the rewriting rules can be added.
> 
> @chengsijin0817 this is ready for you to continue now. Notice that I have refactored things a bit, after #70. Most importantly, for the sake of simplicity, I have merged the two concrete classes for the example rule into just one file with only one actual class (see: [RuleConvertTPAddIndexNLJToHashJoin.java](https://github.com/LiUSemWeb/HeFQUIN/blob/main/src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/rewriting/rules/RuleConvertTPAddIndexNLJToHashJoin.java)). You can use the same pattern for the other rules.

Thanks, I will create a new branch and add more rewriting rules in the same pattern.

**Comment by hartig** [comment]
Parts of this issue have been addressed by PR #93

**Comment by hartig** [comment]
Further rules have been added by PR #97

**Comment by hartig** [comment]
@chengsijin0817 which groups of rules are still missing?

**Comment by chengsijin0817** [comment]
> @chengsijin0817 which groups of rules are still missing?

Rules related to operators join, union, mj, and mu still need to be added.

**Comment by chengsijin0817** [comment]
This issue has been addressed by PR #102
